import {
  ChevronLeft,
  ChevronRight,
  Copy,
  CreditCard,
  File,
  Home,
  LineChart,
  ListFilter,
  MoreVertical,
  Package,
  Package2,
  PanelLeft,
  Search,
  Settings,
  ShoppingCart,
  Truck,
  Users2,
  X,
  Check,
  AlertCircle,
  Eye,
  EyeOff,
  Loader2,
  Mail,
  Lock,
  User,
  Phone,
  Building,
  MapPin,
  Calendar,
  DollarSign,
  Heart,
  Star,
  Image as ImageIcon,
  Upload,
  Trash2,
  Edit,
  Plus,
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Menu,
  Sun,
  Moon,
  Github,
  Twitter,
  Linkedin,
  Instagram,
  Facebook,
  Youtube,
  Globe,
  Languages,
  Filter,
  SearchX,
  FileText,
  Clock,
  Bell,
  Settings2,
  HelpCircle,
  Info,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  RefreshCw,
  LogOut,
  LogIn,
  UserPlus,
  UserCheck,
  UserX,
  Users,
  Map as MapIcon,
} from 'lucide-react';

export type Icon = typeof Home;

export const Icons = {
  spinner: Loader2,
  google: () => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className="h-4 w-4"
    >
      <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z" />
    </svg>
  ),
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  copy: Copy,
  creditCard: CreditCard,
  file: File,
  home: Home,
  lineChart: LineChart,
  listFilter: ListFilter,
  moreVertical: MoreVertical,
  package: Package,
  package2: Package2,
  panelLeft: PanelLeft,
  search: Search,
  settings: Settings,
  shoppingCart: ShoppingCart,
  truck: Truck,
  users2: Users2,
  x: X,
  check: Check,
  alertCircle: AlertCircle,
  eye: Eye,
  eyeOff: EyeOff,
  mail: Mail,
  lock: Lock,
  user: User,
  phone: Phone,
  building: Building,
  mapPin: MapPin,
  calendar: Calendar,
  dollarSign: DollarSign,
  heart: Heart,
  star: Star,
  image: ImageIcon,
  upload: Upload,
  trash: Trash2,
  edit: Edit,
  plus: Plus,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  externalLink: ExternalLink,
  menu: Menu,
  sun: Sun,
  moon: Moon,
  globe: Globe,
  languages: Languages,
  filter: Filter,
  searchX: SearchX,
  fileText: FileText,
  clock: Clock,
  bell: Bell,
  settings2: Settings2,
  helpCircle: HelpCircle,
  info: Info,
  alertTriangle: AlertTriangle,
  checkCircle2: CheckCircle2,
  xCircle: XCircle,
  refreshCw: RefreshCw,
  logOut: LogOut,
  logIn: LogIn,
  userPlus: UserPlus,
  userCheck: UserCheck,
  userX: UserX,
  users: Users,
  map: MapIcon,
  github: Github,
};